name: ci

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

env:
  TEST_TAG: zibdie/atlassian-playwright:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run Venv
        run: printenv
      - name: Run Venv
        run: echo ${TEST_TAG}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Build Test Image
        run: |
          docker build -t testimg ./testfolder/
      - name: Remove Test Image
        run: |
          echo "Test was successful, removing test image"
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: zibdie/atlassian-playwright:latest
